R: 75
T: 150
m: 3
n: 4
# unique_scope: [row_sets, col_sets]
unique_scope: [row_sets]
uniformity: strict
position_balance: true
seed:
  mode: integer
  value: 20250824
  engine: py_random
card_id_mode: sequential
card_number_start: 1
bbd_mode: auto
colors: auto
log_level: INFO
out_cards: cards.json
out_report: report.json
summary_csv: summary.csv

